config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :posts do
    resources :comments
  end
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
  </div>
  <% if user_signed_in? %>
  <p>
    <%= link_to 'Delete', [comment.post, comment],
                method: :delete,
                class: "button",
                data: { confirm: 'Delete your comment?' }
                %>
  </p>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fupuplog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", class:"imglogo" %>
      <% end %>
    </div>
    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li><%= link_to "About", about_path %></li>
    </ul>

    <ul>
      <li class="category">Social</li>
      <li><a href="https://twitter.com/fupuchu">Twitter</a></li>
      <li><a href="http://instagram.com/fupuchu">Instagram</a></li>
      <li><a href="https://github.com/fupuchu">Github</a></li>
      <li><a href="https://inbox.google.com">Email</a></li>
    </ul>
    <% if user_signed_in? %>
      <p class="sign_in">Admin Login</p>
      <% end %>
  </div>

  <div id="main_content">
    <div id="header">
      <% if current_page?(root_path) %>
      <p>All Posts</p>
      <% elsif current_page?(about_path) %>
      <p>About</p>
      <% else %>
      <%= link_to "Back to all Posts", root_path %>
      <% end %>
      <% if user_signed_in? %>
      <div class="buttons">
        <button class="button"><%= link_to "New Post", new_post_path %></button>
        <button class="button"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></button>
      </div>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class:"alert") %>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
   <%= image_tag "avatar.png" %>
  </div>
  <div id="content">
    <h1>I'm Snoels/Fupuchu</h1>
    <h1>TL;DR I'm Potato</h1>
    <h2>I have a potato for a brain</h2>
    <h3>LF> Moar Potatoes</h3>
    <%= image_tag "snoels.jpg" %>

  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
    <div id="errors">
      <h5><%= pluralize(@post.errors.count, "error") %> prevented this post from being posted!</h5>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li style="color:red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.cktext_area :body, rows: 10 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Blog Post</h1>
 <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
<div class="post_wrapper">
  <h2 class="title"><%= link_to post.title.html_safe, post %></h2>
  <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
  <p class="body"><%= post.body.html_safe %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Blog Post</h1>
 <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
    <%= @post.title.html_safe %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if user_signed_in? %>
    <button class="button"><%= link_to 'Edit', edit_post_path(@post) %></button>
    <button class="button"><%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: ' Are you sure?' } %></button>
    <% end %>
  </p>

  <p>
    <%= @post.body.html_safe %>
  </p>
  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>